#!/usr/bin/env python3
"""Compatibility facade for the canonical NRDR lateral-attribution tool."""

from openpilot.nrdr.tools.lateral.attribution import (
  ANGLE_EDGES_DEG,
  DEFAULT_LOOKAHEADS_M,
  MAX_LANE_STD,
  MAX_LANE_WIDTH_M,
  MAX_PATH_STD,
  MIN_CURVATURE,
  MIN_LANE_PROB,
  MIN_LANE_WIDTH_M,
  MPS_TO_MPH,
  RELEVANT_PARAMS,
  REQUIRED_SERVICES,
  SPEED_EDGES_MPH,
  Context,
  ControllerReading,
  ControlSample,
  DelaySample,
  LaneSample,
  ScanResult,
  build_parser,
  build_report,
  classify_attribution,
  collect,
  decode_params,
  expand_sources,
  extract_controller_reading,
  finite,
  finite_median,
  fraction,
  infer_yaw_sign,
  is_fresh,
  lane_observation,
  logged_steer_ratio_model_policy,
  main,
  param_bool,
  parse_edges,
  percentile,
  print_report,
  route_id,
  sign,
  strict_matched_evidence,
  summarize_controls,
  summarize_delay,
  summarize_lanes,
)


__all__ = (
  "ANGLE_EDGES_DEG",
  "DEFAULT_LOOKAHEADS_M",
  "MAX_LANE_STD",
  "MAX_LANE_WIDTH_M",
  "MAX_PATH_STD",
  "MIN_CURVATURE",
  "MIN_LANE_PROB",
  "MIN_LANE_WIDTH_M",
  "MPS_TO_MPH",
  "RELEVANT_PARAMS",
  "REQUIRED_SERVICES",
  "SPEED_EDGES_MPH",
  "Context",
  "ControllerReading",
  "ControlSample",
  "DelaySample",
  "LaneSample",
  "ScanResult",
  "build_parser",
  "build_report",
  "classify_attribution",
  "collect",
  "decode_params",
  "expand_sources",
  "extract_controller_reading",
  "finite",
  "finite_median",
  "fraction",
  "infer_yaw_sign",
  "is_fresh",
  "lane_observation",
  "logged_steer_ratio_model_policy",
  "main",
  "param_bool",
  "parse_edges",
  "percentile",
  "print_report",
  "route_id",
  "sign",
  "strict_matched_evidence",
  "summarize_controls",
  "summarize_delay",
  "summarize_lanes",
)


if __name__ == "__main__":
  raise SystemExit(main())
