"""Generate and validate NRDR's typed parameter registry artifacts."""

from __future__ import annotations

import argparse
from collections.abc import Iterable
from pathlib import Path
import re
import sys

if __package__:
  from .specs import ADDED_PARAM_SPECS, OVERRIDDEN_PARAM_SPECS, PARAM_SPECS, ParamSpec, validate_catalog
else:
  # Keep direct execution independent of importing the openpilot package.
  sys.path.insert(0, str(Path(__file__).resolve().parent))
  from specs import ADDED_PARAM_SPECS, OVERRIDDEN_PARAM_SPECS, PARAM_SPECS, ParamSpec, validate_catalog


GENERATED_NOTICE = "Generated by openpilot/nrdr/params/generate.py; do not edit."
CPP_INCLUDE = '#include "../nrdr/params/generated/params_keys.inc"'
HEADER_ENTRY_RE = re.compile(r'\{"(?P<key>[^"]+)",\s*\{(?P<attributes>.*?)\}\},')


def repository_root() -> Path:
  return Path(__file__).resolve().parents[3]


def _symbol_for(key: str) -> str:
  symbol = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", key)
  symbol = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", symbol)
  symbol = re.sub(r"[^A-Za-z0-9]+", "_", symbol).strip("_").upper()
  if symbol and symbol[0].isdigit():
    symbol = f"KEY_{symbol}"
  return symbol


def render_python_keys(specs: Iterable[ParamSpec] = PARAM_SPECS) -> str:
  specs = tuple(specs)
  lines = [
    '"""Typed NRDR parameter keys.  Generated; do not edit by hand."""',
    "",
    "from enum import StrEnum",
    "",
    "",
    "class NrdrParamKey(StrEnum):",
  ]
  lines.extend(f'  {_symbol_for(spec.key)} = "{spec.key}"' for spec in specs)
  lines.extend((
    "",
    "",
    "ADDED_KEYS: frozenset[NrdrParamKey] = frozenset((",
  ))
  lines.extend(f"  NrdrParamKey.{_symbol_for(spec.key)}," for spec in ADDED_PARAM_SPECS)
  lines.extend((
    "))",
    "",
    "OVERRIDDEN_KEYS: frozenset[NrdrParamKey] = frozenset((",
  ))
  lines.extend(f"  NrdrParamKey.{_symbol_for(spec.key)}," for spec in OVERRIDDEN_PARAM_SPECS)
  lines.extend((
    "))",
    "",
    "ALL_KEYS: frozenset[NrdrParamKey] = ADDED_KEYS | OVERRIDDEN_KEYS",
    "",
  ))
  return "\n".join(lines)


def render_python_init() -> str:
  return "\n".join((
    '"""Generated NRDR parameter key exports."""',
    "",
    "from .keys import ADDED_KEYS, ALL_KEYS, OVERRIDDEN_KEYS, NrdrParamKey",
    "",
    '__all__ = ("ADDED_KEYS", "ALL_KEYS", "NrdrParamKey", "OVERRIDDEN_KEYS")',
    "",
  ))


def render_cpp_include(specs: Iterable[ParamSpec] = ADDED_PARAM_SPECS) -> str:
  lines = [f"// {GENERATED_NOTICE}"]
  lines.extend(f'    {{"{spec.key}", {{{spec.cpp_attributes}}}}},' for spec in specs)
  return "\n".join(lines) + "\n"


def generated_targets(root: Path | None = None) -> dict[Path, str]:
  root = root or repository_root()
  generated_dir = root / "openpilot" / "nrdr" / "params" / "generated"
  return {
    generated_dir / "__init__.py": render_python_init(),
    generated_dir / "keys.py": render_python_keys(),
    generated_dir / "params_keys.inc": render_cpp_include(),
  }


def _header_entries(header: str) -> tuple[dict[str, str], tuple[str, ...]]:
  entries: dict[str, str] = {}
  duplicates: list[str] = []
  for match in HEADER_ENTRY_RE.finditer(header):
    key = match.group("key")
    if key in entries:
      duplicates.append(key)
    entries[key] = match.group("attributes")
  return entries, tuple(duplicates)


def repository_errors(root: Path | None = None) -> tuple[str, ...]:
  root = root or repository_root()
  errors = list(validate_catalog())

  symbols: dict[str, str] = {}
  for spec in PARAM_SPECS:
    symbol = _symbol_for(spec.key)
    if symbol in symbols:
      errors.append(f"generated Python identifier collision: {symbols[symbol]} and {spec.key} -> {symbol}")
    symbols[symbol] = spec.key

  for path, expected in generated_targets(root).items():
    if not path.is_file():
      errors.append(f"missing generated file: {path.relative_to(root)}")
    elif path.read_text(encoding="utf-8") != expected:
      errors.append(f"stale generated file: {path.relative_to(root)}")

  header_path = root / "openpilot" / "common" / "params_keys.h"
  if not header_path.is_file():
    errors.append(f"missing parameter registry: {header_path.relative_to(root)}")
    return tuple(errors)

  header = header_path.read_text(encoding="utf-8")
  if header.count(CPP_INCLUDE) != 1:
    errors.append(f"params_keys.h must contain exactly one {CPP_INCLUDE}")

  direct_entries, duplicates = _header_entries(header)
  if duplicates:
    errors.append(f"duplicate direct params_keys.h entries: {', '.join(sorted(duplicates))}")

  for spec in ADDED_PARAM_SPECS:
    if spec.key in direct_entries:
      errors.append(f"{spec.key}: generated key must not also be declared directly in params_keys.h")

  for spec in OVERRIDDEN_PARAM_SPECS:
    actual = direct_entries.get(spec.key)
    if actual is None:
      errors.append(f"{spec.key}: overridden existing key is missing from params_keys.h")
    elif actual != spec.cpp_attributes:
      errors.append(f"{spec.key}: registry metadata mismatch: expected {{{spec.cpp_attributes}}}, got {{{actual}}}")

  return tuple(errors)


def write_generated(root: Path | None = None) -> None:
  root = root or repository_root()
  catalog_errors = validate_catalog()
  if catalog_errors:
    raise ValueError("invalid catalog:\n" + "\n".join(f"- {error}" for error in catalog_errors))
  for path, content in generated_targets(root).items():
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--check", action="store_true", help="fail instead of rewriting stale generated files")
  args = parser.parse_args()

  if not args.check:
    write_generated()

  errors = repository_errors()
  if errors:
    print("NRDR parameter registry validation failed:", file=sys.stderr)
    for error in errors:
      print(f"  - {error}", file=sys.stderr)
    return 1
  print("NRDR parameter registry is current")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
