#pragma once

#include <string>
#include <unordered_map>

#include "openpilot/cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"AlwaysOnDM", {PERSISTENT | BACKUP, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"DisableUpdates", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DisengageOnAccelerator", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"DriverLockoutCount", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, INT, "0"}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY | BACKUP, BOOL}},
    {"ExperimentalMode", {PERSISTENT | BACKUP, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT | BACKUP, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT | BACKUP, STRING}},
    {"GithubUsername", {PERSISTENT | BACKUP, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT | BACKUP, STRING}},
    {"GsmMetered", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT | BACKUP, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"HondaBoschARadar", {PERSISTENT, BOOL, "1"}},
    {"HondaGasFactorParams", {PERSISTENT, FLOAT}},
    {"HondaWindFactorParams", {PERSISTENT, FLOAT}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"IsLiveStreaming", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"IsMetric", {PERSISTENT | BACKUP, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT | BACKUP, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT | BACKUP, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LivestreamEncoderBitrate", {CLEAR_ON_MANAGER_START | DONT_LOG, INT}},
    {"LivestreamRequestKeyframe", {CLEAR_ON_MANAGER_START | DONT_LOG, BOOL}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT | BACKUP, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT | BACKUP, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ChestnutBranch", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT | BACKUP, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RecordFront", {PERSISTENT | BACKUP, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"RemoteAccessPinEnabled", {PERSISTENT, BOOL}},
    {"RemoteAccessPinSalt", {PERSISTENT | DONT_LOG, BYTES}},
    {"RemoteAccessPinHash", {PERSISTENT | DONT_LOG, BYTES}},
    {"RemoteAccessPinIterations", {PERSISTENT, INT, "150000"}},
    {"LiveViewEnabled", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"LiveView", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SecOCKey", {PERSISTENT | DONT_LOG | BACKUP, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TorqueBar", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"ChestnutActive", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"ChestnutLoading", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"Version", {PERSISTENT, STRING}},

    // --- sunnypilot params --- //
    {"ApiCache_DriveStats", {PERSISTENT, JSON}},
    {"AutoLaneChangeBsmDelay", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"AutoLaneChangeTimer", {PERSISTENT | BACKUP, INT, "0"}},
    {"BlinkerLateralReengageDelay", {PERSISTENT | BACKUP, INT, "0"}},  // seconds
    {"BlinkerMinLateralControlSpeed", {PERSISTENT | BACKUP, INT, "20"}},  // MPH or km/h
    {"BlinkerPauseLateralControl", {PERSISTENT | BACKUP, INT, "0"}},
    {"Brightness", {PERSISTENT | BACKUP, INT, "0"}},
    {"CarList", {PERSISTENT, JSON}},
    {"CarParamsSP", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsSPCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsSPPersistent", {PERSISTENT, BYTES}},
    {"CarPlatformBundle", {PERSISTENT | BACKUP, JSON}},
    {"ChevronInfo", {PERSISTENT | BACKUP, INT, "4"}},
    {"CompletedSunnylinkConsentVersion", {PERSISTENT, STRING, "0"}},
    {"CustomAccIncrementsEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"CustomAccLongPressIncrement", {PERSISTENT | BACKUP, INT, "5"}},
    {"CustomAccShortPressIncrement", {PERSISTENT | BACKUP, INT, "1"}},
    {"DeviceBootMode", {PERSISTENT | BACKUP, INT, "0"}},
    {"DevUIInfo", {PERSISTENT | BACKUP, INT, "0"}},
    {"EnableCopyparty", {PERSISTENT | BACKUP, BOOL}},
    {"EnableGithubRunner", {PERSISTENT | BACKUP, BOOL}},
    {"GreenLightAlert", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"GithubRunnerSufficientVoltage", {CLEAR_ON_MANAGER_START , BOOL}},
    {"HasAcceptedTermsSP", {PERSISTENT, STRING, "0"}},
    {"HideVEgoUI", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"IntelligentCruiseButtonManagement", {PERSISTENT | BACKUP , BOOL}},
    {"InteractivityTimeout", {PERSISTENT | BACKUP, INT, "0"}},
    {"IsDevelopmentBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsReleaseSpBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"LaneCentering", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"LaneCenteringE2EAuthority", {PERSISTENT | BACKUP, FLOAT, "1.0"}},
    {"LaneCenteringPauseOnSignal", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"LaneCenterOffset", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"LastGPSPositionLLK", {PERSISTENT, STRING}},
    {"LeadDepartAlert", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"MaxTimeOffroad", {PERSISTENT | BACKUP, INT, "1800"}},
    {"ModelRunnerTypeCache", {CLEAR_ON_ONROAD_TRANSITION, INT}},
    {"OffroadMode", {CLEAR_ON_MANAGER_START, BOOL}},
    {"Offroad_TiciSupport", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadScreenOffBrightness", {PERSISTENT | BACKUP, INT, "0"}},
    {"OnroadScreenOffBrightnessMigrated", {PERSISTENT | BACKUP, STRING, "0.0"}},
    {"OnroadScreenOffTimer", {PERSISTENT | BACKUP, INT, "15"}},
    {"OnroadScreenOffTimerMigrated", {PERSISTENT | BACKUP, STRING, "0.0"}},
    {"OnroadUploads", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"QuickBootToggle", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"QuietMode", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RainbowMode", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RoadEdgeLaneChangeEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RocketFuel", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ScreenSaverEnabled", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"ScreenSaverTimeout", {PERSISTENT | BACKUP, INT, "300"}},
    {"ShowAdvancedControls", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ShowTurnSignals", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"StandstillTimer", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TrueVEgoUI", {PERSISTENT | BACKUP, BOOL, "0"}},

    // MADS params
    {"Mads", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"MadsMainCruiseAllowed", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"MadsSteeringMode", {PERSISTENT | BACKUP, INT, "0"}},
    {"MadsUnifiedEngagementMode", {PERSISTENT | BACKUP, BOOL, "1"}},

    // Model Manager params
    {"ModelManager_ActiveBundle", {PERSISTENT, JSON}},
    {"ModelManager_ActiveBundleUSBGPU", {PERSISTENT, JSON}}, //TODO-SP: kept for migration, remove on next sync?
    {"ModelManager_ActiveBundleChestnut", {PERSISTENT, JSON}},
    {"ModelManager_ActiveJson", {CLEAR_ON_MANAGER_START, JSON}},
    {"ModelManager_ClearCache", {CLEAR_ON_MANAGER_START, BOOL}},
    {"ModelManager_DownloadRef", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"ModelManager_Favs", {PERSISTENT | BACKUP, STRING}},
    {"ModelManager_LastSyncTime", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"ModelManager_LastSyncTime_Chestnut", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"ModelManager_ModelsCache", {PERSISTENT | BACKUP, JSON}},
    {"ModelManager_ModelsCache_Chestnut", {PERSISTENT | BACKUP, JSON}},

    // Neural Network Lateral Control
    {"NeuralNetworkLateralControl", {PERSISTENT | BACKUP, BOOL, "0"}},

    // sunnylink params
    {"EnableSunnylinkUploader", {PERSISTENT | BACKUP, BOOL}},
    {"LastSunnylinkPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"ParamsVersion", {PERSISTENT, INT}},
    {"SunnylinkCache_Roles", {PERSISTENT, STRING}},
    {"SunnylinkCache_Users", {PERSISTENT, STRING}},
    {"SunnylinkDongleId", {PERSISTENT, STRING}},
    {"SunnylinkdPid", {PERSISTENT, INT}},
    {"SunnylinkEnabled", {PERSISTENT, BOOL, "1"}},
    {"SunnylinkTempFault", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0"}},

    // Backup Manager params
    {"BackupManager_CreateBackup", {PERSISTENT, BOOL}},
    {"BackupManager_RestoreVersion", {PERSISTENT, STRING}},

    // sunnypilot car specific params
    {"HondaEnforceStockLongitudinal", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"HyundaiLongitudinalTuning", {PERSISTENT | BACKUP, INT, "0"}},
    {"SubaruStopAndGo", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"SubaruStopAndGoManualParkingBrake", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TeslaCoopSteering", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TeslaMadsScreenButton", {PERSISTENT | BACKUP, INT, "0"}},
    {"ToyotaEnforceStockLongitudinal", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ToyotaStopAndGoHack", {PERSISTENT | BACKUP, BOOL, "0"}},

    {"DynamicExperimentalControl", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"BlindSpot", {PERSISTENT | BACKUP, BOOL, "0"}},

    // sunnypilot model params
    {"CameraOffset", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"LagdToggle", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"LagdToggleDelay", {PERSISTENT | BACKUP, FLOAT, "0.2"}},
    {"LagdValueCache", {PERSISTENT, FLOAT, "0.2"}},
    {"LaneTurnDesire", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"LaneTurnValue", {PERSISTENT | BACKUP, FLOAT, "19.0"}},
    {"PlanplusControl", {PERSISTENT | BACKUP, FLOAT, "1.0"}},

    // mapd
    {"MapAdvisorySpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT}},
    {"Mapd_ClearCache", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MapdVersion", {PERSISTENT, STRING}},
    {"MapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT, "0.0"}},
    {"NextMapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_OSMUpdateRequired", {CLEAR_ON_MANAGER_START, JSON}},
    {"OsmDbUpdatesCheck", {CLEAR_ON_MANAGER_START, BOOL}},  // mapd database update happens with device ON, reset on boot
    {"OSMDownloadBounds", {PERSISTENT, STRING}},
    {"OsmDownloadedDate", {PERSISTENT, STRING, "0.0"}},
    {"OSMDownloadLocations", {PERSISTENT, JSON}},
    {"OSMDownloadProgress", {CLEAR_ON_MANAGER_START, JSON}},
    {"OsmLocal", {PERSISTENT, BOOL}},
    {"OsmLocationName", {PERSISTENT, STRING}},
    {"OsmLocationTitle", {PERSISTENT, STRING}},
    {"OsmLocationUrl", {PERSISTENT, STRING}},
    {"OsmStateName", {PERSISTENT, STRING, "All"}},
    {"OsmStateTitle", {PERSISTENT, STRING}},
    {"OsmWayTest", {PERSISTENT, STRING}},
    {"RoadName", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"RoadNameToggle", {PERSISTENT | BACKUP, BOOL, "0"}},

    // Speed Limit
    {"SpeedLimitMode", {PERSISTENT | BACKUP, INT, "1"}},
    {"SpeedLimitOffsetType", {PERSISTENT | BACKUP, INT, "0"}},
    {"SpeedLimitPolicy", {PERSISTENT | BACKUP, INT, "3"}},
    {"SpeedLimitValueOffset", {PERSISTENT | BACKUP, INT, "0"}},

    // Smart Cruise Control
    {"MapTargetVelocities", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"SmartCruiseControlMap", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"SmartCruiseControlVision", {PERSISTENT | BACKUP, BOOL, "0"}},

    {"LatPScaleLowSpeed", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatPScaleStandard", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatPScaleHighway", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatIScaleLowSpeed", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatIScaleStandard", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatIScaleHighway", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatFScaleLowSpeed", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatFScaleStandard", {PERSISTENT | BACKUP, INT, "100"}},
    {"LatFScaleHighway", {PERSISTENT | BACKUP, INT, "100"}},
    {"LongPidTuneScale", {PERSISTENT | BACKUP, INT, "100"}},
    {"LongPidTuneScaleAggressive", {PERSISTENT | BACKUP, INT, "200"}},
    {"LongPidTuneScaleStandard", {PERSISTENT | BACKUP, INT, "100"}},
    {"LongPidTuneScaleRelaxed", {PERSISTENT | BACKUP, INT, "80"}},
    {"LongPidTuneScaleEcon", {PERSISTENT | BACKUP, INT, "50"}},
    {"NrdrCruiseMismatchCorrection", {PERSISTENT | BACKUP, FLOAT, "100"}},
    {"NrdrCruiseOverspeedAllowance", {PERSISTENT | BACKUP, INT, "0"}},
    {"HondaCenterScale", {PERSISTENT | BACKUP, FLOAT, "0.5"}},
    // Legacy HondaPidFriction is intentionally retained as a tombstone. The
    // interpolated controller owns the six dedicated settings below.
    {"HondaPidFriction", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"NrdrInterpolatedTorquePifBlend", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrInterpolatedTorqueShare", {PERSISTENT | BACKUP, INT, "50"}},
    {"NrdrInterpolatedTorqueLatAccelFactor", {PERSISTENT | BACKUP, FLOAT, "5.0"}},
    {"NrdrInterpolatedTorqueFriction", {PERSISTENT | BACKUP, FLOAT, "0.12"}},
    {"NrdrInterpolatedTorqueFrictionStandard", {PERSISTENT | BACKUP, FLOAT, "0.10"}},
    {"NrdrInterpolatedTorqueFrictionHighway", {PERSISTENT | BACKUP, FLOAT, "0.06"}},
    {"HondaNotchEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"HondaNotchFreq", {PERSISTENT | BACKUP, FLOAT, "7.5"}},
    {"HondaNotchQ", {PERSISTENT | BACKUP, FLOAT, "1.5"}},
    {"NrdrSteerRatioMode", {PERSISTENT | BACKUP, INT, "0"}},
    {"NrdrSteerRatioManualCenter", {PERSISTENT | BACKUP, FLOAT, "15.38"}},
    {"NrdrSteerRatioManualFinal", {PERSISTENT | BACKUP, FLOAT, "10.93"}},
    // Legacy steer-ratio tombstones. Keep these registered for migration and
    // downgrade compatibility; active code must use the three keys above.
    {"NrdrLearnSteerRatio", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrSteerRatioCenterClarity", {PERSISTENT | BACKUP, FLOAT, "18.50"}},
    {"NrdrSteerRatioOuterClarity", {PERSISTENT | BACKUP, FLOAT, "12.72"}},
    {"NrdrSteerRatioCenterCivic", {PERSISTENT | BACKUP, FLOAT, "17.24"}},
    {"NrdrSteerRatioOuterCivic", {PERSISTENT | BACKUP, FLOAT, "10.93"}},
    {"NrdrSteerRatioCenterAccord", {PERSISTENT | BACKUP, FLOAT, "18.31"}},
    {"NrdrSteerRatioOuterAccord", {PERSISTENT | BACKUP, FLOAT, "11.82"}},
    {"NrdrSteerRatioCenterCrv5g", {PERSISTENT | BACKUP, FLOAT, "17.94"}},
    {"NrdrSteerRatioOuterCrv5g", {PERSISTENT | BACKUP, FLOAT, "12.30"}},
    {"NrdrSteerRatioCenterInsight", {PERSISTENT | BACKUP, FLOAT, "16.82"}},
    {"NrdrSteerRatioOuterInsight", {PERSISTENT | BACKUP, FLOAT, "12.58"}},
    {"NrdrLegacyDualBpSteerRatio", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"NrdrLaneChangeEndpointSteerRatio", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"NrdrSteerRatioOffset", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"NrdrSteerRatioMin", {PERSISTENT | BACKUP, FLOAT, "16.84"}},
    {"NrdrSteerRatioMax", {PERSISTENT | BACKUP, FLOAT, "12.74"}},
    {"NrdrLearnStiffness", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"NrdrLearnAngleOffset", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"HondaStoppingDecelRate", {PERSISTENT | BACKUP, INT, "30"}},
    {"NrdrIncreaseOverrideTolerance", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrDriverOverrideThreshold", {PERSISTENT | BACKUP, INT, "1400"}},
    {"NrdrOverrideThresholdCenterBoost", {PERSISTENT | BACKUP, INT, "1000"}},
    {"HondaOverrideFadeDownSecs", {PERSISTENT | BACKUP, FLOAT, "0.1"}},
    {"HondaOverrideFadeUpSecs", {PERSISTENT | BACKUP, FLOAT, "0.1"}},
    {"HondaOverrideTorqueScale", {PERSISTENT | BACKUP, INT, "0"}},
    {"HondaDriverAssistDuringOverride", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"HondaLiveLearningGas", {PERSISTENT | BACKUP, BOOL}},
    {"HondaTorqueLowPassFilter", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"HondaLpfTauLowSpeed", {PERSISTENT | BACKUP, FLOAT, "0.1"}},
    {"HondaLpfTauStandard", {PERSISTENT | BACKUP, FLOAT, "0.1"}},
    {"HondaLpfTauHighway", {PERSISTENT | BACKUP, FLOAT, "0.05"}},
    {"NrdrFirstRunSetupDone", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrAutoSelectModel", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"StaticFeedforwardLong", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"NrdrHondaEcuMatchedLong", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrHondaFullBrakeAuthority", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"NrdrRoenAccelerationLimits", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"HondaInjectionTest", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"HondaAltDashboardSpeed", {PERSISTENT | BACKUP, INT, "0"}},
    {"HondaAltDashboardDistance", {PERSISTENT | BACKUP, INT, "0"}},
    {"NrdrHondaDashVariantB", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrClearDashFaults", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"HondaSpoofCameraMessages", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrCruiseButtonSubMode", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrCruiseButtonSubModeSecs", {PERSISTENT | BACKUP, INT, "15"}},
    {"NrdrHudSubModeUntil", {CLEAR_ON_MANAGER_START, FLOAT, "0"}},
    {"NrdrRemoteForceUpdate", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"NrdrRemoteTuneScan", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"NrdrRemoteStatus", {CLEAR_ON_MANAGER_START, STRING, "idle"}},
    {"NrdrTuneReportSummary", {PERSISTENT, STRING}},
    {"NrdrCarTuneInfo", {PERSISTENT, STRING}},
    {"NrdrCarTuneDetails", {PERSISTENT, STRING}},
    {"NrdrCarControllerInfo", {PERSISTENT, STRING}},
    {"NrdrCarHandcraftedInfo", {PERSISTENT, STRING}},
    {"NrdrCarPidLowInfo", {PERSISTENT, STRING}},
    {"NrdrCarPidMidInfo", {PERSISTENT, STRING}},
    {"NrdrCarPidHighInfo", {PERSISTENT, STRING}},
    {"NrdrCarDampingInfo", {PERSISTENT, STRING}},
    {"NrdrCarCenterInfo", {PERSISTENT, STRING}},
    {"NrdrCarNnlcInfo", {PERSISTENT, STRING}},
    {"NrdrCarSteerRatioInfo", {PERSISTENT, STRING}},
    {"NrdrCarLearningInfo", {PERSISTENT, STRING}},
    {"NrdrCarHelpersInfo", {PERSISTENT, STRING}},
    {"NrdrStarPilotPid", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrHandcraftedLateralTune", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrNnlcEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrNnlcActivationSpeed", {PERSISTENT | BACKUP, INT, "30"}},
    {"NrdrNnlcKpGain", {PERSISTENT | BACKUP, INT, "100"}},
    {"NrdrNnlcKfGain", {PERSISTENT | BACKUP, INT, "50"}},
    {"NrdrNnlcKiGain", {PERSISTENT | BACKUP, INT, "10"}},
    {"NrdrTuneLearner", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"NrdrLatStiction", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"NrdrTuneLearnerReset", {PERSISTENT, BOOL, "0"}},
    {"NrdrTuneLearnerStrength", {PERSISTENT | BACKUP, INT, "100"}},
    {"NrdrTuneLearnerRate", {PERSISTENT | BACKUP, INT, "50"}},
    {"NrdrTuneLearnerMap", {PERSISTENT | BACKUP | DONT_LOG, BYTES}},
    {"HondaCenterBoostThreshold", {PERSISTENT | BACKUP, FLOAT, "3"}},
    {"HondaCenterBoostMinSpeed", {PERSISTENT | BACKUP, INT, "50"}},
    {"NrdrLatRateDamping", {PERSISTENT | BACKUP, INT, "30"}},
    {"NrdrLatRateDampingFadeSpeed", {PERSISTENT | BACKUP, INT, "30"}},
    {"HondaSteerDeltaLimiter", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"HondaSteerDeltaUp", {PERSISTENT | BACKUP, FLOAT, "3"}},
    {"HondaSteerDeltaDown", {PERSISTENT | BACKUP, FLOAT, "3"}},
    {"HondaPidTuneScale", {PERSISTENT | BACKUP, INT, "100"}},
    {"HondaStopAccel", {PERSISTENT | BACKUP, FLOAT, "-2"}},
    {"HondaStoppingDecelRateLong", {PERSISTENT | BACKUP, FLOAT, "0.3"}},
    {"HondaVEgoStopping", {PERSISTENT | BACKUP, FLOAT, "0.5"}},
    {"HondaVEgoStarting", {PERSISTENT | BACKUP, FLOAT, "0.5"}},
    {"HondaCivicRadarTryout", {PERSISTENT | BACKUP, BOOL, "0"}},

    // Torque lateral control custom params
    {"CustomTorqueParams", {PERSISTENT | BACKUP , BOOL}},
    {"EnforceTorqueControl", {PERSISTENT | BACKUP, BOOL}},
    {"LateralJerkTorqueController", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"LiveTorqueParamsToggle", {PERSISTENT | BACKUP , BOOL}},
    {"LiveTorqueParamsRelaxedToggle", {PERSISTENT | BACKUP , BOOL}},
    {"TorqueControlTune", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"TorqueParamsOverrideEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TorqueParamsOverrideFriction", {PERSISTENT | BACKUP, FLOAT, "0.1"}},
    {"TorqueParamsOverrideLatAccelFactor", {PERSISTENT | BACKUP, FLOAT, "2.5"}},
};
